[build]
  publish = "." # Your static files (like index.html) are in the root
  functions = "netlify/functions" # Your functions are in netlify/functions relative to the root

[[plugins]]
package = "@netlify/plugin-functions-install-core"
